name: "build 1 - python"

on:
  push:
    paths:
      - 'build1.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_USR }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
#############################################################################################

       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
#############################################################################################
       - name: Cleaning up disk space & building packages in parallel
         timeout-minutes: 350
         continue-on-error: true
         env:
           PYPI_KEY: '${{ secrets.CFT1 }}'
         run: |
           parallel -u ::: \
           'wget ${{ secrets.CLEANL }} && sudo bash cleanup.sh' \
           'git clone -b test https://${{ secrets.PU }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.PU }}/${{ secrets.PUR }} 1 && cd 1 && sudo docker-compose up --build'
